itsmekori/eng-1015-update-button-component
infinity-keys/the-scene pull request #17
Opened 2023-09-05 21:40 UTC by IvySwing

2023-09-06 14:56 UTC, stormcloud266 requested changes

2023-09-06 14:56 UTC, stormcloud266 commented on web/src/components/Button/Button.tsx
> +    { 'bg-accent': !color }
All we are going to need here are the different border colors and the fullwidth, since the bg color will only be the accent color on hover. We can delete the outline prop as well. So all the buttons will be `bg-neutral-750 hover:bg-accent/30`

Let's use an `accent` prop that makes the border the accent color if it's true, and white if it's false (basically just rename the `border` prop to `accent`).

2023-09-06 14:56 UTC, stormcloud266 commented on web/src/components/Button/Button.tsx
> +  children = 'click here',
Let's make sure this default text is removed

2023-09-06 15:15 UTC, illepic approved these changes

2023-09-07 18:14 UTC, stormcloud266 approved these changes

2023-09-07 18:14 UTC, merged